import { useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowUpRight, BarChart3, Bell, Check, ChevronRight,
  CircleDollarSign, Clock3, Database, FileCheck2, Filter, Gauge, LayoutDashboard,
  Menu, MoreHorizontal, Play, RefreshCw, Search, Settings2, ShieldCheck,
  Sparkles, Target, WalletCards, Zap,
} from 'lucide-react'

type Page = 'Command center' | 'Recovery pipeline' | 'Cases' | 'Experiments' | 'Exceptions' | 'Policy center'
type CaseStatus = 'Recovered' | 'In review' | 'Retrying' | 'Stopped'
type Case = { id:string; customer:string; merchant:string; amount:number; reason:string; probability:number; action:string; attempts:number; status:CaseStatus; date:string }
const cases:Case[]=[
  {id:'EVT_0001',customer:'Customer 1',merchant:'Spotify',amount:199,reason:'Insufficient funds',probability:.61,action:'Silent retry',attempts:1,status:'Recovered',date:'Today, 18:41'},
  {id:'EVT_0002',customer:'Customer 2',merchant:'Netflix India',amount:4999,reason:'Insufficient funds',probability:.58,action:'Silent retry',attempts:1,status:'Recovered',date:'Today, 18:39'},
  {id:'EVT_0003',customer:'Customer 3',merchant:'GymFlex',amount:4999,reason:'Insufficient funds',probability:.62,action:'Text nudge',attempts:4,status:'In review',date:'Today, 18:37'},
  {id:'EVT_0004',customer:'Customer 4',merchant:'Hotstar',amount:199,reason:'Insufficient funds',probability:.55,action:'Text nudge',attempts:3,status:'Stopped',date:'Today, 18:35'},
  {id:'EVT_0005',customer:'Customer 5',merchant:'Hotstar',amount:199,reason:'Insufficient funds',probability:.60,action:'Silent retry',attempts:1,status:'Recovered',date:'Today, 18:33'},
]
const money=(n:number)=>`₹${n.toLocaleString('en-IN',{maximumFractionDigits:2})}`
const nav:{label:Page;icon:typeof LayoutDashboard}[]=[
  {label:'Command center',icon:LayoutDashboard},{label:'Recovery pipeline',icon:Activity},{label:'Cases',icon:FileCheck2},
  {label:'Experiments',icon:Target},{label:'Exceptions',icon:AlertTriangle},{label:'Policy center',icon:ShieldCheck},
]
export default function App(){
  const [page,setPage]=useState<Page>('Command center'),[open,setOpen]=useState(false),[reviewed,setReviewed]=useState<string[]>([]),[toast,setToast]=useState(''),[query,setQuery]=useState('')
  const pending=cases.filter(c=>c.status==='In review'&&!reviewed.includes(c.id)).length
  const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2600)}
  const approve=(id:string)=>{setReviewed(v=>[...v,id]);notify(`${id} verified. Recovery metrics updated.`)}
  return <div className="app"><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="mark"><Sparkles size={18}/></div><div><b>AAROHAN<span>-X</span></b><small>REVENUE RECOVERY OS</small></div></div><div className="workspace"><i/> Acme subscriptions <ChevronRight size={14}/></div><nav>{nav.map(({label,icon:Icon})=><button className={page===label?'active':''} onClick={()=>{setPage(label);setOpen(false)}} key={label}><Icon size={18}/>{label}{label==='Exceptions'&&pending>0&&<em>{pending}</em>}</button>)}</nav><div className="side-bottom"><div className="system"><b><i/> AI systems operational</b><small>Last sync 2 min ago</small><div><i/><i/><i/><i/><i/></div></div><button className="settings"><Settings2 size={16}/> Workspace settings</button><div className="user"><strong>DS</strong><span>Diksha Sharma<small>Admin</small></span><MoreHorizontal size={17}/></div></div></aside><main><header><button className="mobile" onClick={()=>setOpen(!open)}><Menu/></button><div className="crumb">⌘ Aarohan-X <ChevronRight size={14}/><b>{page}</b></div><div className="top-right"><span className="live"><i/> Live mode</span><button><Bell size={17}/></button><strong>DS</strong></div></header><section className="content">{page==='Command center'&&<Command notify={notify}/>} {page==='Recovery pipeline'&&<Pipeline approve={approve} reviewed={reviewed} notify={notify}/>} {page==='Cases'&&<CasesPage query={query} setQuery={setQuery} approve={approve} reviewed={reviewed}/>} {page==='Experiments'&&<Experiments notify={notify}/>} {page==='Exceptions'&&<Exceptions approve={approve} reviewed={reviewed}/>} {page==='Policy center'&&<Policy notify={notify}/>}</section></main>{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</div>
}
function Title({eyebrow,title,desc,action}:{eyebrow:string;title:string;desc:string;action?:React.ReactNode}){return <div className="title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{desc}</p></div><div className="title-actions">{action}</div></div>}
function Stat({label,value,trend,icon:Icon,tone='' }:{label:string;value:string;trend:string;icon:typeof WalletCards;tone?:string}){return <div className={`stat ${tone}`}><div><span>{label}</span><Icon size={17}/></div><b>{value}</b><small><ArrowUpRight size={13}/>{trend}</small></div>}
function Command({notify}:{notify:(m:string)=>void}){return <><Title eyebrow="MONDAY · 05 SEP 2026" title="Revenue command center" desc="Your AI recovery engine is working across every payment moment." action={<><button className="ghost"><RefreshCw size={15}/> Sync data</button><button className="primary" onClick={()=>notify('Recovery batch completed successfully.')}><Play size={15} fill="currentColor"/> Run recovery batch</button></>}/><div className="stats"><Stat label="Total at risk" value={money(10595)} trend="+12.4% vs last period" icon={CircleDollarSign}/><Stat label="Net recovered" value={money(5595.7)} trend="+18.7% vs last period" icon={WalletCards} tone="green"/><Stat label="Recovery rate" value="52.8%" trend="+8.2 pts this week" icon={Gauge} tone="cyan"/><Stat label="Cost per recovery" value="₹0.08" trend="−34.1% efficiency gain" icon={Zap} tone="amber"/></div><div className="grid two"><Chart/><Funnel/></div><div className="grid lower"><ActivityFeed/><Insights notify={notify}/></div></>}
function Chart(){return <section className="card chart"><Head kicker="RECOVERY PERFORMANCE" title="Revenue recovered"/><div className="legend"><span><i className="green-dot"/> Recovered</span><span><i className="muted-dot"/> At risk</span><b>₹5,595.70 <small>net recovered</small></b></div><div className="graph"><div className="lines"/><svg viewBox="0 0 720 210" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#52d8a5" stopOpacity=".35"/><stop offset="1" stopColor="#52d8a5" stopOpacity="0"/></linearGradient></defs><path d="M0 183C55 169 70 150 125 157S192 132 240 145S300 114 355 126S410 95 468 112S540 78 594 91S670 48 720 60V210H0Z" fill="url(#fill)"/><path d="M0 183C55 169 70 150 125 157S192 132 240 145S300 114 355 126S410 95 468 112S540 78 594 91S670 48 720 60" fill="none" stroke="#52d8a5" strokeWidth="3"/></svg><div><span>30 Aug</span><span>01 Sep</span><span>03 Sep</span><span>05 Sep</span></div></div></section>}
function Head({kicker,title}:{kicker:string;title:string}){return <div className="head"><div><small>{kicker}</small><h2>{title}</h2></div><MoreHorizontal size={18}/></div>}
function Funnel(){return <section className="card funnel"><Head kicker="LIVE FUNNEL" title="Recovery journey"/>{[['Events received','5','100%','blue'],['Diagnosed','5','100%','purple'],['Intervention started','5','100%','violet'],['Payment recovered','4','80%','green']].map(([l,v,w,c])=><div className="funnel-row" key={l}><div><span>{l}</span><b>{v}</b></div><i className={c} style={{width:w}}/></div>)}<footer><ShieldCheck size={15}/> 4 cases recovered automatically</footer></section>}
function ActivityFeed(){return <section className="card"><Head kicker="AUTOMATION FEED" title="Recent recovery activity"/><div className="feed">{[['Payment recovered','Hotstar · ₹199.00','2 min ago','green'],['Text nudge sent','Hotstar · ₹199.00','4 min ago','violet'],['Needs verification','GymFlex · ₹4,999.00','6 min ago','amber'],['Payment recovered','Netflix India · ₹4,999.00','8 min ago','green']].map(([a,b,t,c])=><div key={a+b}><i className={c}><Check size={13}/></i><span><b>{a}</b><small>{b}</small></span><time>{t}</time></div>)}</div></section>}
function Insights({notify}:{notify:(m:string)=>void}){return <section className="card"><Head kicker="AI SIGNALS" title="What needs your attention"/><div className="insight"><i className="green"><ArrowUpRight size={16}/></i><span><b>Ladder strategy is winning</b><small>It recovered ₹20 more than silent retry only.</small></span></div><div className="insight"><i className="amber"><AlertTriangle size={16}/></i><span><b>1 case needs verification</b><small>GymFlex has no payment signal yet.</small></span></div><button className="secondary" onClick={()=>notify('Opening AI recommendations...')}>Review recommendations <ChevronRight size={15}/></button></section>}
function Pipeline({approve,reviewed,notify}:{approve:(id:string)=>void;reviewed:string[];notify:(m:string)=>void}){const cols=[['Diagnosed',[]],['Intervention',[cases[2],cases[3]]],['Payment pending',[]],['Recovered',[cases[0],cases[1],cases[4]]]] as [string,Case[]][];return <><Title eyebrow="OPERATIONS" title="Recovery pipeline" desc="Watch every rupee move from failure to recovery." action={<button className="ghost"><Filter size={15}/> Filters</button>}/><div className="pipeline">{cols.map(([title,items])=><div className="column" key={title}><div className="column-head"><b>{title}</b><span>{items.length}</span></div>{items.length?items.map(item=><CaseCard key={item.id} item={item} approve={approve} reviewed={reviewed} notify={notify}/>):<div className="empty"><Sparkles size={17}/>No cases here</div>}</div>)}</div></>}
function CaseCard({item,approve,reviewed,notify}:{item:Case;approve:(id:string)=>void;reviewed:string[];notify:(m:string)=>void}){const done=reviewed.includes(item.id);return <div className="case-card"><div className="case-top"><code>{item.id}</code><MoreHorizontal size={15}/></div><b>{item.customer}</b><small>{item.merchant}</small><strong>{money(item.amount)}</strong><div className="case-meta"><span>◉ {Math.round(item.probability*100)}% likely</span><span>{item.attempts} attempts</span></div>{item.status==='In review'&&!done?<button className="verify" onClick={()=>approve(item.id)}><FileCheck2 size={13}/> Verify result</button>:done?<div className="verified"><Check size={13}/> Verified by you</div>:<button className="card-link" onClick={()=>notify(`Opened ${item.id}`)}>Open case <ChevronRight size={13}/></button>}</div>}
function CasesPage({query,setQuery,approve,reviewed}:{query:string;setQuery:(v:string)=>void;approve:(id:string)=>void;reviewed:string[]}){const filtered=useMemo(()=>cases.filter(c=>`${c.id} ${c.customer} ${c.merchant}`.toLowerCase().includes(query.toLowerCase())),[query]);return <><Title eyebrow="CASE MANAGEMENT" title="Recovery cases" desc="Every payment event, decision, and outcome in one place." action={<button className="primary"><FileCheck2 size={15}/> Review queue</button>}/><section className="card table-card"><div className="table-tools"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cases, customers, merchants..."/></div><button className="ghost"><Filter size={15}/> Filter</button></div><div className="table-wrap"><table><thead><tr><th>Case</th><th>Customer / merchant</th><th>Amount</th><th>Diagnosis</th><th>AI confidence</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><code>{c.id}</code><small>{c.date}</small></td><td><b>{c.customer}</b><small>{c.merchant}</small></td><td><b>{money(c.amount)}</b></td><td>{c.reason}</td><td><div className="confidence"><i style={{width:`${c.probability*100}%`}}/><b>{Math.round(c.probability*100)}%</b></div></td><td><span className={`status ${c.status.replace(' ','-').toLowerCase()}`}><i/>{reviewed.includes(c.id)?'Verified':c.status}</span></td><td>{c.status==='In review'&&!reviewed.includes(c.id)?<button className="table-verify" onClick={()=>approve(c.id)}>Verify</button>:<MoreHorizontal size={16}/>}</td></tr>)}</tbody></table></div></section></>}
function Exceptions({approve,reviewed}:{approve:(id:string)=>void;reviewed:string[]}){const done=reviewed.includes('EVT_0003');return <><Title eyebrow="HUMAN-IN-THE-LOOP" title="Exceptions & verification" desc="Your review queue for decisions that deserve a human signal." action={<button className="ghost"><Database size={15}/> Export queue</button>}/><div className="exception-banner"><AlertTriangle size={22}/><div><b>{done?0:1} case requires your attention</b><small>Verify outcomes to keep recovery analytics accurate.</small></div><button className="secondary" onClick={()=>approve('EVT_0003')}>Review now <ChevronRight size={15}/></button></div><div className="grid exception-grid"><section className="card"><Head kicker="OPEN REVIEWS" title="Verification queue"/><div className={`exception ${done?'done':''}`}><div className="exception-icon">◉</div><span><b>Customer 3 · GymFlex</b><small>Automated contact completed without a verified payment signal.</small><code>EVT_0003 · ₹4,999 at risk · 6 min ago</code></span>{done?<div className="verified"><Check size={13}/> Verified</div>:<button className="verify" onClick={()=>approve('EVT_0003')}><Check size={13}/> Verify outcome</button>}</div></section><section className="card"><Head kicker="REVIEW GUIDE" title="Before you verify"/>{[['01','Confirm the payment signal','Check your gateway or merchant ledger.'],['02','Verify the final outcome','Approval updates the case and metrics.'],['03','Keep the audit trail','Every action is recorded with your identity.']].map(x=><div className="guide" key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</section></div></>}
function Experiments({notify}:{notify:(m:string)=>void}){const data=[['Silent retry only',5397,3,0],['Full recovery ladder',5596,4,.3],['Contact first',5596,4,.8]] as [string,number,number,number][];return <><Title eyebrow="STRATEGY LAB" title="Recovery experiments" desc="Compare intervention strategies on the same five-event sample." action={<button className="primary" onClick={()=>notify('Experiment started with deterministic seed 42.')}><Play size={15} fill="currentColor"/> Run experiment</button>}/><div className="experiment-hero card"><div><small>RECOMMENDED STRATEGY</small><h2>Full recovery ladder <em>Best net value</em></h2><p>Silent retry first, then contact only when it creates positive expected value.</p></div><strong>₹5,595.70<small>net recovered</small></strong></div><div className="strategy-grid">{data.map(([name,amount,eventCount,cost])=><div className="card strategy" key={name}><div><Target size={17}/>{name}</div><h2>{money(amount)}</h2><small>gross recovered</small><div className="strategy-line"><span>Recovery</span><i><b style={{width:`${amount/60}%`}}/></i><b>{eventCount}/5</b></div><div className="strategy-line"><span>Contact cost</span><i><b className="cost" style={{width:`${Math.max(cost*100,2)}%`}}/></i><b>₹{cost.toFixed(2)}</b></div><button className="card-link">View strategy details <ChevronRight size={13}/></button></div>)}</div><section className="card table-card"><Head kicker="EXPERIMENT OUTPUT" title="Side-by-side comparison"/><div className="table-wrap"><table><thead><tr><th>Strategy</th><th>Gross recovered</th><th>Net recovered</th><th>Events</th><th>Cost</th><th>Result</th></tr></thead><tbody>{data.map(([name,a,e,c])=><tr key={name}><td><b>{name}</b></td><td>{money(a)}</td><td>{money(a-c)}</td><td>{e}/5</td><td>₹{c.toFixed(2)}</td><td>{name==='Full recovery ladder'?<span className="status recovered"><i/>Winner</span>:'Reference'}</td></tr>)}</tbody></table></div></section></>}
function Policy({notify}:{notify:(m:string)=>void}){const [silent,setSilent]=useState(2),[contacts,setContacts]=useState(2),[high,setHigh]=useState(100000);return <><Title eyebrow="GUARDRAILS" title="Policy center" desc="The AI optimizes inside these merchant-approved boundaries." action={<button className="primary" onClick={()=>notify('Policy saved safely.')}><Check size={15}/> Save policy</button>}/><div className="grid policy-grid"><section className="card policy"><Head kicker="RECOVERY LIMITS" title="Automation boundaries"/>{[['Maximum silent retries',silent,setSilent,0,5],['Maximum customer contacts',contacts,setContacts,0,5],['High-value approval threshold',high,setHigh,25000,500000]].map(([label,value,setter,min,max])=><label key={label as string}>{label as string}<b>{label==='High-value approval threshold'?money(value as number):value as number}</b><input type="range" min={min as number} max={max as number} step={label==='High-value approval threshold'?25000:1} value={value as number} onChange={e=>(setter as React.Dispatch<React.SetStateAction<number>>)(Number(e.target.value))}/></label>)}</section><section className="card policy"><Head kicker="CHANNEL CONTROLS" title="Contact preferences"/>{['Silent retry|Zero-cost gateway retry','Text nudges|SMS / WhatsApp payment link','Voice calls|Only above threshold'].map(x=>{const [a,b]=x.split('|');return <div className="toggle-row" key={a}><span><b>{a}</b><small>{b}</small></span><button className="toggle"><i/></button></div>})}<div className="quiet"><Clock3 size={15}/> Quiet hours <b>21:00 — 09:00 IST</b></div></section></div><div className="policy-note"><ShieldCheck size={18}/><span><b>Safe by default</b><small>High-value cases always enter human verification before money-touching actions.</small></span></div></>}
